import React from 'react';
import '../../App.css';
import '../pagination/background.css';
import { DotLottieReact } from '@lottiefiles/dotlottie-react';
import '../animation/LottieAnimation.css';
import { Player as LottiePlayer } from '@lottiefiles/react-lottie-player';

const animationData = require('../animation/AnikiHamster.json'); 

const FiveMinsVideo = () => {
  return (
   <div className='fiveminsvideo'>
      <div style={{display:'block'}}>
        <h2 style={{display:"flex"}}>
            Creating Face/Faceless Video :
            <DotLottieReact
                src="https://lottie.host/63e43fb7-61be-486f-aef2-622b144f7fc1/2m8UGcP8KR.json"
                loop
                autoplay
                style={{
                     maxWidth: "100px",
                    marginTop:"-12px", marginLeft:"6px"
                }}                  
             /> 
        </h2>
        <ul>
         <h3>Below Apps are used to create faceless / face 5 mins videos </h3>
          <ul>
            <li>
                <a href='https://chatgpt.com/' target="_blank" rel="noopener noreferrer" style={{textDecoration:"none", color:"black", display:"flex"}}>
                    ChatGPT - Can you make me a 5 mins video script on Sam Altman?   
                    <DotLottieReact
                        src="https://assets-global.website-files.com/64f6f2c0e3f4c5a91c1e823a/651308644ce6b51c9d6e41db_Training.json"
                        loop
                        autoplay
                        style={{
                            maxWidth: "100px",
                            marginTop:"-12px", marginLeft:"20px"
                        }}                  
                    />   
                </a>
            </li>
            <li><a href='https://elevenlabs.io/' target="_blank" rel="noopener noreferrer" style={{textDecoration:"none", color:"black", display:"flex"}}>
                    Upload Script generated by ChatGPT here to make a audo file of the script, choose different voices here
                    <DotLottieReact
                        src="https://assets-global.website-files.com/64f6f2c0e3f4c5a91c1e823a/6513085d8864477543fdaf83_Fine-tuning.json"
                        loop
                        autoplay
                        style={{
                            maxWidth: "100px",
                            marginTop:"-12px", marginLeft:"20px"
                        }}                  
                    />   
                </a>
            </li>
            <li><a href='https://ai.invideo.io/' target="_blank" rel="noopener noreferrer" style={{textDecoration:"none", color:"black", display:"flex"}}>
                    Upload Audio file generated in previous step or upload a script generated in 1st step here to generate video , will create faceless video here
                    <DotLottieReact
                        src="https://assets-global.website-files.com/64f6f2c0e3f4c5a91c1e823a/6513086769f8866123aa5c0d_GPU.json"
                        loop
                        autoplay
                        style={{
                            maxWidth: "100px",
                            marginTop:"-12px", marginLeft:"20px"
                        }}                  
                    />   
                </a>
            </li>
            <li><a href='https://www.movioai.tech/' target="_blank" rel="noopener noreferrer" style={{textDecoration:"none", color:"black", display:"flex"}}>
                    Create Face video on this site, by uploading script audio file
                    <DotLottieReact
                        src="https://assets-global.website-files.com/64f6f2c0e3f4c5a91c1e823a/65130796c5e81529f319b892_Inference.json"
                        loop
                        autoplay
                        style={{
                            maxWidth: "100px",
                            marginTop:"-12px", marginLeft:"20px"
                        }}                  
                    />   
                </a>
            </li>
            <li><a href='https://youtube.com' target="_blank" rel="noopener noreferrer" style={{textDecoration:"none", color:"black", display:"flex"}}>
                    You can upload generated video fiel to youtube, you can generate any no of video withhout using a camera
                    <DotLottieReact
                        src="https://assets-global.website-files.com/64f6f2c0e3f4c5a91c1e823a/6542785d6d2211bb782506c1_Control.json"
                        loop
                        autoplay
                        style={{
                            maxWidth: "100px",
                            marginTop:"-12px", marginLeft:"20px"
                        }}                  
                    />   
                </a>
            </li>           
          </ul>        
        </ul> 
        <br/>      
        <hr/>
        <br/>
        <h3>You can reach us @  </h3>
        <p>Mobile: 93478 39890 | 63005 44805</p>     
        <p>Email: rajapinja@laraidsolutions.com | raja.pinja@gmail.com | raja_pinja@yahoo.com </p>     
       
      </div>      
    </div>     

  );
}

export default FiveMinsVideo;
